[color]
background = 0xf7f2ec
foreground = 0x437085

[editor]
code_editor = true
code_editor_lang = "text"
soft_wrap = true
line_number = false
indent_guides = false

[debug]
#log = false

[file_tree.scrollbar.hz]
move_to_right_at_launch = 55
